name: deploy to aws ec2

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Only deploy if the triggering workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{ secrets.EC2_PRIVATE_KEY}}
          script: |
            sudo docker pull rambaranwal/devops-test-backend:latest
            sudo docker pull rambaranwal/devops-test-frontend:latest
            sudo docker rm -f devops-test-backend || true
            sudo docker rm -f devops-test-frontend || true
            sudo docker network create devops-network || true
            sudo docker run -d -p 5000:3000 --name devops-test-backend --network devops-network rambaranwal/devops-test-backend:latest
            sudo docker run -d -p 80:80 --name devops-test-frontend --network devops-network rambaranwal/devops-test-frontend:latest